# Generated by Django 5.0.1 on 2024-03-08 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameBN', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('DateK', models.DateTimeField(default=datetime.datetime(2024, 3, 8, 19, 38, 6, 205933))),
                ('CCCD', models.CharField(max_length=20)),
            ],
        ),
    ]
