# Generated by Django 5.0.1 on 2024-03-08 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_benhnhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='DateK',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 20, 5, 58, 318357)),
        ),
    ]
