# Generated by Django 5.0.1 on 2024-03-15 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_benhnhan_datek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='DateK',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 21, 46, 240834)),
        ),
    ]
