# Generated by Django 5.0.1 on 2024-03-22 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_phongkham_alter_benhnhan_datek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='DateK',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 22, 18, 3, 770616)),
        ),
    ]
