# Generated by Django 5.0.1 on 2024-03-27 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_benhnhan_datek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='DateK',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 14, 10, 44, 980052)),
        ),
    ]
